### PR TITLE
Enable test suite to run on sd nodes.

### PR DESCRIPTION
**Pull request by ryanattard**
Signed-off-by: Ryan Attard <ryanattard@ryanattard.info>

### CODE REVIEW

**Comment by damien-lemoal** [comment]
@ryanattard I just did the same last week but forgot to push the change :)
I just did now. Please try it.

Note: If you could test the patch I suggested for fio issue #953, it would be really great !

**Comment by ryanattard** [comment]
I've been super swamped. I'll follow up on that thread tomorrow (I did test it but I wanted to come back with better data!)

**Comment by damien-lemoal** [comment]
OK. Great.

What about this issue ? Can I close it ? Does my fix work for you ?

**Comment by ryanattard** [comment]
Verified your patch.

**Comment by damien-lemoal** [comment]
Thanks !

**Pull request closed without merging**
